### ISSUE TITLE
'NoneType' object has no attribute 'endswith'

### ISSUE THREAD

**Issue by henryhao1991** [paulrozdeba/varanneal#4]
In line 87 of va_ode.py, it uses 'endswith', but stime_file is none type by default, which will cause this error. Probably check if stime_file is none or not before this line?

**Comment by paulrozdeba** [comment]
Thanks for pointing this out; I've fixed this bug in commit a8c26a3 of the master branch, and it will be included in the next release.

**Comment by paulrozdeba** [comment]
Thanks for pointing this out; I've fixed this bug in commit a8c26a3 of the master branch, and it will be included in the next release.
